//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trigger4
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyUser
    {
        public int ID { get; set; }
        public string GUI { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Companies { get; set; }
        public string Triggers { get; set; }
        public string Email { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> BillingCycle { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Newsletter { get; set; }
        public string Results { get; set; }
    }
}
